apiVersion: v1
kind: Service
metadata:
  name: udagram-user-api
  labels:
    service: udagram-user-api
spec:
  selector:
    service: udagram-user-api
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
